/* eslint-disable sort-keys */
export const IMAGE_PATHS = {
  APOLLO_ICON: '/images/skill-icon/Apollo.png',
  ATRAE: '/images/Atrae.png',
  BACKGROUND_TOP_IMAGE: '/images/BackgroundTopImage.png',
  CHAKRA_ICON: '/images/skill-icon/Chakra.png',
  CROSSDOOR: '/images/Crossdoor.png',
  CSS_ICON: '/images/skill-icon/Css.png',
  DART_ICON: '/images/skill-icon/Dart.png',
  FIGMA_ICON: '/images/skill-icon/Figma.png',
  FLUTTER_ICON: '/images/skill-icon/Flutter.png',
  GRAPHQL_ICON: '/images/skill-icon/GraphQL.png',
  HTML_ICON: '/images/skill-icon/Html.png',
  ILLUST_ICON: '/images/skill-icon/Illust.png',
  JAVASCRIPT_ICON: '/images/skill-icon/JS.png',
  MANTINE_ICON: '/images/skill-icon/Mantine.png',
  MY_IMAGE: '/images/MyImage.png',
  NEXTJS_ICON: '/images/skill-icon/Next.js.png',
  NOIGZAKA_APP_MOCK: '/images/NogizakaAppMock.png',
  NUXT_ICON: '/images/skill-icon/Nuxt.png',
  PHOTOSHOP_ICON: '/images/skill-icon/Photoshop.png',
  PORTFOLIO_APPLICATION: '/images/PortfolioApplication.png',
  PORTFOLIO_MOCK: '/images/PortfolioMock.png',
  PORTFOLIO_MY_IMAGE: '/images/PortfolioMyImage.png',
  PORTFOLIO_NOTE: '/images/PortfolioNote.png',
  REACT_ICON: '/images/skill-icon/React.png',
  SAMPLE: '/images/sample.png',
  SUPABASE_ICON: '/images/skill-icon/Supabase.png',
  TAILWIND_ICON: '/images/skill-icon/Tailwind.png',
  TYPESCRIPT_ICON: '/images/skill-icon/TS.png',
  VERCEL_ICON: '/images/skill-icon/Vercel.png',
  VUETIFY_ICON: '/images/skill-icon/Vuetify.png',
  VUE_ICON: '/images/skill-icon/Vue.png',
} as const;
