/* eslint-disable sort-keys */
export const IMAGE_PATHS = {
  APOLLO_ICON: '/images/skill-icon/Apollo-500x500.png',
  ATRAE: '/images/ATRAE_1024x768.png',
  BACKGROUND_TOP_IMAGE: '/images/BACKGROUND_PORTFOLIO_TOP.png',
  CHAKRA_ICON: '/images/skill-icon/Chakra-500x500.png',
  CROSSDOOR: '/images/CROSSDOOR_1024x768.png',
  CSS_ICON: '/images/skill-icon/CSS-500x500.png',
  DART_ICON: '/images/skill-icon/Dart-500x500.png',
  FIGMA_ICON: '/images/skill-icon/Figma-500x500.png',
  FLUTTER_ICON: '/images/skill-icon/Flutter-500x500.png',
  GRAPHQL_ICON: '/images/skill-icon/GraphQL-500x500.png',
  HTML_ICON: '/images/skill-icon/HTML-500x500.png',
  ILLUST_ICON: '/images/skill-icon/Illust-500x500.png',
  JAVASCRIPT_ICON: '/images/skill-icon/JavaScript-500x500.png',
  MANTINE_ICON: '/images/skill-icon/Mantine-500x500.png',
  MY_IMAGE: '/images/MY_IMAGE.png',
  NEXTJS_ICON: '/images/skill-icon/Next.js-500x500.png',
  NOIGZAKA_APP_MOCK: '/images/NOGIZAKA_APP_MOCK.png',
  NUXT_ICON: '/images/skill-icon/Nuxt-500x500.png',
  PHOTOSHOP_ICON: '/images/skill-icon/Photoshop-500x500.png',
  PORTFOLIO: '/images/PORTFOLIO_1920x1080.png',
  PORTFOLIO_APPLICATION: '/images/PORTFOLIO_APPLICATION.png',
  PORTFOLIO_MOCK: '/images/PORTFOLIO_MOCK.png',
  PORTFOLIO_MY_IMAGE: '/images/PORTFOLIO_MY_IMAGE.png',
  PORTFOLIO_NOTE: '/images/PORTFOLIO_NOTE.png',
  REACT_ICON: '/images/skill-icon/React-500x500.png',
  SAMPLE: '/images/sample.png',
  TAILWIND_ICON: '/images/skill-icon/Tailwind-500x500.png',
  TYPESCRIPT_ICON: '/images/skill-icon/TypeScript-500x500.png',
  VERCEL_ICON: '/images/skill-icon/Vercel-500x500.png',
  VUETIFY_ICON: '/images/skill-icon/Vuetify-500x500.png',
  VUE_ICON: '/images/skill-icon/Vue-500x500.png',
} as const;
